---
# tasks file for role_export_credential_input_sources

- name: Export credential Input Sources Block
  block:

  - name: Create a new token using username/password
    ansible.controller.token:
      description: 'Token for Controller API Lookup - ALWAYS DELETE ME IF FOUND'
      scope: "read"
      state: present
      controller_host: "{{ controller_hostname }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      validate_certs: "{{ controller_validate_certs }}"

  - name: "Set API Endpoint URL"
    ansible.builtin.set_fact:
      api_endpoint: "{{ controller_hostname }}/api/v2/credential_input_sources/?page_size={{ page_size }}{{ query_args }}"
      current_page: "1"

  - name: "Setup Variable To Return Results"
    ansible.builtin.set_fact:
      input_sources_results: []

  - name: "Get {{ collection }}"
    ansible.builtin.include_tasks: query_api.yml

  - name: Write to File
    ansible.builtin.template:
      src: '{{ yaml_file }}.j2'
      dest: '{{ yaml_file }}'
      mode: '0644'

  always:
    - name: Delete our Token with the token we created
      ansible.controller.token:
        existing_token: "{{ controller_token }}"
        state: absent
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"

...
